import { type Smoothness } from './coefficients';
export type CloseType = 'OPEN' | 'CLOSE';
export type Dimension = 2 | 3;
export type Point = [number, number] | [number, number, number];
export type PointList = Point[];
export type Vertex = [number, number] | [number, number, number];
export type VertexList = Vertex[];
export type BezierCanvas = {
    dimension: Dimension;
    beginPath: () => void;
    moveTo: (x: number, y: number, z?: number) => void;
    lineTo: (x: number, y: number, z?: number) => void;
    closePath: (closeType?: CloseType) => void;
    beginDash: () => void;
    endDash: () => void;
};
export declare function _getCanvasUtils(canvas: any): BezierCanvas;
export declare function _validateSmoothness(smoothness: number): Smoothness;
export declare function _concentrate(pointList: PointList, close?: boolean): PointList;
export declare function _copy(arr: PointList, target?: PointList): PointList;
export declare function _samePoints(a: PointList, b: PointList): boolean;
export declare function _getCloseCurvePoints(pointList: PointList): PointList;
export declare function _interpolateVertex(v1: Vertex, v2: Vertex, t: number): Vertex;
